// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `map_unwrap_err_bio`, `map_unwrap_err_rewrap`, `map_unwrap_err_write`, `map_unwrap_err`, `map_vault_err_create`, `map_vault_err_write`, `map_vault_err`, `map_wrap_err_bio`, `map_wrap_err_rewrap`, `map_wrap_err`, `unlock_inner`, `with_vault_key`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Unwraps the backup blob with `passphrase_utf8`, opens `borrowers.db` at
/// `db_path`, and returns all vault rows. The passphrase bytes are zeroed
/// before returning; the derived key never crosses this boundary.
///
/// `passphrase_utf8` is taken by value so we own and can wipe it.
Future<VaultContents> unlockAndReadVault({
  required List<int> passphraseUtf8,
  required String blob,
  required String dbPath,
}) => RustLib.instance.api.crateApiUnlockAndReadVault(
  passphraseUtf8: passphraseUtf8,
  blob: blob,
  dbPath: dbPath,
);

/// Inserts a borrower; returns the new id.
Future<PlatformInt64> insertBorrower({
  required List<int> passphraseUtf8,
  required String blob,
  required String dbPath,
  required String name,
  String? contact,
  String? notes,
}) => RustLib.instance.api.crateApiInsertBorrower(
  passphraseUtf8: passphraseUtf8,
  blob: blob,
  dbPath: dbPath,
  name: name,
  contact: contact,
  notes: notes,
);

/// Updates an existing borrower by id.
Future<void> updateBorrower({
  required List<int> passphraseUtf8,
  required String blob,
  required String dbPath,
  required PlatformInt64 id,
  required String name,
  String? contact,
  String? notes,
}) => RustLib.instance.api.crateApiUpdateBorrower(
  passphraseUtf8: passphraseUtf8,
  blob: blob,
  dbPath: dbPath,
  id: id,
  name: name,
  contact: contact,
  notes: notes,
);

/// Deletes a borrower by id (blocked by FK if loans still reference them).
Future<void> deleteBorrower({
  required List<int> passphraseUtf8,
  required String blob,
  required String dbPath,
  required PlatformInt64 id,
}) => RustLib.instance.api.crateApiDeleteBorrower(
  passphraseUtf8: passphraseUtf8,
  blob: blob,
  dbPath: dbPath,
  id: id,
);

/// Inserts a loan; returns the new id. The `borrower_id` FK is enforced.
Future<PlatformInt64> insertLoan({
  required List<int> passphraseUtf8,
  required String blob,
  required String dbPath,
  required PlatformInt64 bookId,
  required PlatformInt64 borrowerId,
  required PlatformInt64 lentDate,
  PlatformInt64? dueDate,
  PlatformInt64? returnedDate,
  String? notes,
}) => RustLib.instance.api.crateApiInsertLoan(
  passphraseUtf8: passphraseUtf8,
  blob: blob,
  dbPath: dbPath,
  bookId: bookId,
  borrowerId: borrowerId,
  lentDate: lentDate,
  dueDate: dueDate,
  returnedDate: returnedDate,
  notes: notes,
);

/// Updates a loan by id.
Future<void> updateLoan({
  required List<int> passphraseUtf8,
  required String blob,
  required String dbPath,
  required PlatformInt64 id,
  required PlatformInt64 bookId,
  required PlatformInt64 borrowerId,
  required PlatformInt64 lentDate,
  PlatformInt64? dueDate,
  PlatformInt64? returnedDate,
  String? notes,
}) => RustLib.instance.api.crateApiUpdateLoan(
  passphraseUtf8: passphraseUtf8,
  blob: blob,
  dbPath: dbPath,
  id: id,
  bookId: bookId,
  borrowerId: borrowerId,
  lentDate: lentDate,
  dueDate: dueDate,
  returnedDate: returnedDate,
  notes: notes,
);

/// Deletes a loan by id.
Future<void> deleteLoan({
  required List<int> passphraseUtf8,
  required String blob,
  required String dbPath,
  required PlatformInt64 id,
}) => RustLib.instance.api.crateApiDeleteLoan(
  passphraseUtf8: passphraseUtf8,
  blob: blob,
  dbPath: dbPath,
  id: id,
);

/// Creates a new empty encrypted vault at `db_path` and returns its
/// `backup_blob` (`base64(salt).base64(iv).base64(ciphertext)`). The passphrase
/// bytes are wiped before returning; the vault key never leaves Rust.
Future<String> createVault({
  required List<int> passphraseUtf8,
  required String dbPath,
}) => RustLib.instance.api.crateApiCreateVault(
  passphraseUtf8: passphraseUtf8,
  dbPath: dbPath,
);

/// Re-wraps the vault key from (`old_passphrase_utf8`, `blob`) under
/// `new_passphrase_utf8`, returning the new `backup_blob`
/// (`base64(salt).base64(iv).base64(ciphertext)`). Both passphrase buffers are
/// wiped before returning; the vault key never leaves Rust and the DB is not
/// opened (the key is unchanged, so existing rows stay readable).
Future<String> rewrapBlob({
  required List<int> oldPassphraseUtf8,
  required List<int> newPassphraseUtf8,
  required String blob,
}) => RustLib.instance.api.crateApiRewrapBlob(
  oldPassphraseUtf8: oldPassphraseUtf8,
  newPassphraseUtf8: newPassphraseUtf8,
  blob: blob,
);

/// Unwraps MK from (`active_secret_utf8`, `blob`), generates a fresh 32-byte
/// CSPRNG secret S, and returns `(S, wrap_vault_key(S, MK))`. The active secret
/// bytes are wiped before returning; MK stays in Rust `Zeroizing<>` and never
/// crosses FFI. S is returned by value because it is meant to be stored.
Future<BiometricWrap> wrapForBiometric({
  required List<int> activeSecretUtf8,
  required String blob,
}) => RustLib.instance.api.crateApiWrapForBiometric(
  activeSecretUtf8: activeSecretUtf8,
  blob: blob,
);

/// The pair produced by enrolling biometric unlock: the random secret `S` to
/// store in hardware-backed storage, and `blob` = `wrap_vault_key(S, MK)`.
class BiometricWrap {
  /// 32-byte CSPRNG secret to seal in the platform keystore (biometric-gated).
  final Uint8List secret;

  /// The MK re-wrapped under `secret`: `base64(salt).base64(iv).base64(ct)`.
  final String blob;

  const BiometricWrap({required this.secret, required this.blob});

  @override
  int get hashCode => secret.hashCode ^ blob.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BiometricWrap &&
          runtimeType == other.runtimeType &&
          secret == other.secret &&
          blob == other.blob;
}

class Borrower {
  final PlatformInt64 id;
  final String? name;
  final String? contact;
  final String? notes;

  const Borrower({required this.id, this.name, this.contact, this.notes});

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ contact.hashCode ^ notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Borrower &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          contact == other.contact &&
          notes == other.notes;
}

class Loan {
  final PlatformInt64 id;
  final PlatformInt64 bookId;
  final PlatformInt64 borrowerId;
  final PlatformInt64? lentDate;
  final PlatformInt64? dueDate;
  final PlatformInt64? returnedDate;
  final String? notes;

  const Loan({
    required this.id,
    required this.bookId,
    required this.borrowerId,
    this.lentDate,
    this.dueDate,
    this.returnedDate,
    this.notes,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      bookId.hashCode ^
      borrowerId.hashCode ^
      lentDate.hashCode ^
      dueDate.hashCode ^
      returnedDate.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Loan &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          bookId == other.bookId &&
          borrowerId == other.borrowerId &&
          lentDate == other.lentDate &&
          dueDate == other.dueDate &&
          returnedDate == other.returnedDate &&
          notes == other.notes;
}

@freezed
sealed class VaultBiometricError
    with _$VaultBiometricError
    implements FrbException {
  const VaultBiometricError._();

  /// Active blob malformed / corrupt → `BackupCorruptFailure`.
  const factory VaultBiometricError.corrupt(String field0) =
      VaultBiometricError_Corrupt;

  /// The active secret did not unwrap the blob → `WrongPassphraseFailure`.
  const factory VaultBiometricError.wrongPassphrase() =
      VaultBiometricError_WrongPassphrase;

  /// Generating/wrapping under the new secret failed → `CryptoFailure`.
  const factory VaultBiometricError.wrap(String field0) =
      VaultBiometricError_Wrap;
}

/// Result of unlocking + reading the borrowers vault from a backup archive.
class VaultContents {
  final List<Borrower> borrowers;
  final List<Loan> loans;

  const VaultContents({required this.borrowers, required this.loans});

  @override
  int get hashCode => borrowers.hashCode ^ loans.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultContents &&
          runtimeType == other.runtimeType &&
          borrowers == other.borrowers &&
          loans == other.loans;
}

@freezed
sealed class VaultCreateError with _$VaultCreateError implements FrbException {
  const VaultCreateError._();

  /// A file already exists at `db_path`, or the DB could not be created.
  /// Maps to `StorageFailure` — the caller chose the path.
  const factory VaultCreateError.alreadyExists(String field0) =
      VaultCreateError_AlreadyExists;

  /// SQLCipher keying/schema failed → `CryptoFailure`.
  const factory VaultCreateError.vaultOpen(String field0) =
      VaultCreateError_VaultOpen;

  /// Key generation or wrap (Argon2id/AES-GCM) failed → `CryptoFailure`.
  const factory VaultCreateError.wrap(String field0) = VaultCreateError_Wrap;
}

@freezed
sealed class VaultRewrapError with _$VaultRewrapError implements FrbException {
  const VaultRewrapError._();

  /// Old blob malformed / corrupt → `BackupCorruptFailure`.
  const factory VaultRewrapError.corrupt(String field0) =
      VaultRewrapError_Corrupt;

  /// OLD passphrase did not unwrap the blob (GCM tag fail) →
  /// `WrongPassphraseFailure`.
  const factory VaultRewrapError.wrongPassphrase() =
      VaultRewrapError_WrongPassphrase;

  /// Re-wrapping under the new passphrase failed (KDF/AEAD) → `CryptoFailure`.
  const factory VaultRewrapError.wrap(String field0) = VaultRewrapError_Wrap;
}

@freezed
sealed class VaultUnlockError with _$VaultUnlockError implements FrbException {
  const VaultUnlockError._();

  /// Blob malformed / archive corrupt → `BackupCorruptFailure`.
  const factory VaultUnlockError.corrupt(String field0) =
      VaultUnlockError_Corrupt;

  /// Argon2id/AES-GCM tag failed → `WrongPassphraseFailure`.
  const factory VaultUnlockError.wrongPassphrase() =
      VaultUnlockError_WrongPassphrase;

  /// SQLCipher open/read failed → `CryptoFailure`.
  const factory VaultUnlockError.vaultOpen(String field0) =
      VaultUnlockError_VaultOpen;
}

@freezed
sealed class VaultWriteError with _$VaultWriteError implements FrbException {
  const VaultWriteError._();

  /// Blob malformed / archive corrupt → `BackupCorruptFailure`.
  const factory VaultWriteError.corrupt(String field0) =
      VaultWriteError_Corrupt;

  /// Argon2id/AES-GCM tag failed → `WrongPassphraseFailure`.
  const factory VaultWriteError.wrongPassphrase() =
      VaultWriteError_WrongPassphrase;

  /// SQLCipher open/key/read failed → `CryptoFailure`.
  const factory VaultWriteError.vaultOpen(String field0) =
      VaultWriteError_VaultOpen;

  /// A constraint (FK ON DELETE RESTRICT / NOT NULL) blocked the write →
  /// `ValidationFailure` (e.g. "borrower still has active loans").
  const factory VaultWriteError.constraint(String field0) =
      VaultWriteError_Constraint;

  /// update/delete targeted an id that does not exist → `NotFoundFailure`.
  const factory VaultWriteError.notFound() = VaultWriteError_NotFound;
}
