// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BiometricWrap dco_decode_biometric_wrap(dynamic raw);

  @protected
  Borrower dco_decode_borrower(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<Borrower> dco_decode_list_borrower(dynamic raw);

  @protected
  List<Loan> dco_decode_list_loan(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  Loan dco_decode_loan(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VaultBiometricError dco_decode_vault_biometric_error(dynamic raw);

  @protected
  VaultContents dco_decode_vault_contents(dynamic raw);

  @protected
  VaultCreateError dco_decode_vault_create_error(dynamic raw);

  @protected
  VaultRewrapError dco_decode_vault_rewrap_error(dynamic raw);

  @protected
  VaultUnlockError dco_decode_vault_unlock_error(dynamic raw);

  @protected
  VaultWriteError dco_decode_vault_write_error(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BiometricWrap sse_decode_biometric_wrap(SseDeserializer deserializer);

  @protected
  Borrower sse_decode_borrower(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<Borrower> sse_decode_list_borrower(SseDeserializer deserializer);

  @protected
  List<Loan> sse_decode_list_loan(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Loan sse_decode_loan(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VaultBiometricError sse_decode_vault_biometric_error(
    SseDeserializer deserializer,
  );

  @protected
  VaultContents sse_decode_vault_contents(SseDeserializer deserializer);

  @protected
  VaultCreateError sse_decode_vault_create_error(SseDeserializer deserializer);

  @protected
  VaultRewrapError sse_decode_vault_rewrap_error(SseDeserializer deserializer);

  @protected
  VaultUnlockError sse_decode_vault_unlock_error(SseDeserializer deserializer);

  @protected
  VaultWriteError sse_decode_vault_write_error(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_biometric_wrap(BiometricWrap self, SseSerializer serializer);

  @protected
  void sse_encode_borrower(Borrower self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_borrower(List<Borrower> self, SseSerializer serializer);

  @protected
  void sse_encode_list_loan(List<Loan> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_loan(Loan self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_vault_biometric_error(
    VaultBiometricError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_vault_contents(VaultContents self, SseSerializer serializer);

  @protected
  void sse_encode_vault_create_error(
    VaultCreateError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_vault_rewrap_error(
    VaultRewrapError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_vault_unlock_error(
    VaultUnlockError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_vault_write_error(
    VaultWriteError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
