// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 780142040;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'pitak_crypto',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiCreateVault({
    required List<int> passphraseUtf8,
    required String dbPath,
  });

  Future<void> crateApiDeleteBorrower({
    required List<int> passphraseUtf8,
    required String blob,
    required String dbPath,
    required PlatformInt64 id,
  });

  Future<void> crateApiDeleteLoan({
    required List<int> passphraseUtf8,
    required String blob,
    required String dbPath,
    required PlatformInt64 id,
  });

  Future<PlatformInt64> crateApiInsertBorrower({
    required List<int> passphraseUtf8,
    required String blob,
    required String dbPath,
    required String name,
    String? contact,
    String? notes,
  });

  Future<PlatformInt64> crateApiInsertLoan({
    required List<int> passphraseUtf8,
    required String blob,
    required String dbPath,
    required PlatformInt64 bookId,
    required PlatformInt64 borrowerId,
    required PlatformInt64 lentDate,
    PlatformInt64? dueDate,
    PlatformInt64? returnedDate,
    String? notes,
  });

  Future<String> crateApiRewrapBlob({
    required List<int> oldPassphraseUtf8,
    required List<int> newPassphraseUtf8,
    required String blob,
  });

  Future<VaultContents> crateApiUnlockAndReadVault({
    required List<int> passphraseUtf8,
    required String blob,
    required String dbPath,
  });

  Future<void> crateApiUpdateBorrower({
    required List<int> passphraseUtf8,
    required String blob,
    required String dbPath,
    required PlatformInt64 id,
    required String name,
    String? contact,
    String? notes,
  });

  Future<void> crateApiUpdateLoan({
    required List<int> passphraseUtf8,
    required String blob,
    required String dbPath,
    required PlatformInt64 id,
    required PlatformInt64 bookId,
    required PlatformInt64 borrowerId,
    required PlatformInt64 lentDate,
    PlatformInt64? dueDate,
    PlatformInt64? returnedDate,
    String? notes,
  });

  Future<BiometricWrap> crateApiWrapForBiometric({
    required List<int> activeSecretUtf8,
    required String blob,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiCreateVault({
    required List<int> passphraseUtf8,
    required String dbPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(passphraseUtf8, serializer);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_vault_create_error,
        ),
        constMeta: kCrateApiCreateVaultConstMeta,
        argValues: [passphraseUtf8, dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateVaultConstMeta => const TaskConstMeta(
    debugName: "create_vault",
    argNames: ["passphraseUtf8", "dbPath"],
  );

  @override
  Future<void> crateApiDeleteBorrower({
    required List<int> passphraseUtf8,
    required String blob,
    required String dbPath,
    required PlatformInt64 id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(passphraseUtf8, serializer);
          sse_encode_String(blob, serializer);
          sse_encode_String(dbPath, serializer);
          sse_encode_i_64(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_vault_write_error,
        ),
        constMeta: kCrateApiDeleteBorrowerConstMeta,
        argValues: [passphraseUtf8, blob, dbPath, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeleteBorrowerConstMeta => const TaskConstMeta(
    debugName: "delete_borrower",
    argNames: ["passphraseUtf8", "blob", "dbPath", "id"],
  );

  @override
  Future<void> crateApiDeleteLoan({
    required List<int> passphraseUtf8,
    required String blob,
    required String dbPath,
    required PlatformInt64 id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(passphraseUtf8, serializer);
          sse_encode_String(blob, serializer);
          sse_encode_String(dbPath, serializer);
          sse_encode_i_64(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_vault_write_error,
        ),
        constMeta: kCrateApiDeleteLoanConstMeta,
        argValues: [passphraseUtf8, blob, dbPath, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeleteLoanConstMeta => const TaskConstMeta(
    debugName: "delete_loan",
    argNames: ["passphraseUtf8", "blob", "dbPath", "id"],
  );

  @override
  Future<PlatformInt64> crateApiInsertBorrower({
    required List<int> passphraseUtf8,
    required String blob,
    required String dbPath,
    required String name,
    String? contact,
    String? notes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(passphraseUtf8, serializer);
          sse_encode_String(blob, serializer);
          sse_encode_String(dbPath, serializer);
          sse_encode_String(name, serializer);
          sse_encode_opt_String(contact, serializer);
          sse_encode_opt_String(notes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_vault_write_error,
        ),
        constMeta: kCrateApiInsertBorrowerConstMeta,
        argValues: [passphraseUtf8, blob, dbPath, name, contact, notes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInsertBorrowerConstMeta => const TaskConstMeta(
    debugName: "insert_borrower",
    argNames: ["passphraseUtf8", "blob", "dbPath", "name", "contact", "notes"],
  );

  @override
  Future<PlatformInt64> crateApiInsertLoan({
    required List<int> passphraseUtf8,
    required String blob,
    required String dbPath,
    required PlatformInt64 bookId,
    required PlatformInt64 borrowerId,
    required PlatformInt64 lentDate,
    PlatformInt64? dueDate,
    PlatformInt64? returnedDate,
    String? notes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(passphraseUtf8, serializer);
          sse_encode_String(blob, serializer);
          sse_encode_String(dbPath, serializer);
          sse_encode_i_64(bookId, serializer);
          sse_encode_i_64(borrowerId, serializer);
          sse_encode_i_64(lentDate, serializer);
          sse_encode_opt_box_autoadd_i_64(dueDate, serializer);
          sse_encode_opt_box_autoadd_i_64(returnedDate, serializer);
          sse_encode_opt_String(notes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_vault_write_error,
        ),
        constMeta: kCrateApiInsertLoanConstMeta,
        argValues: [
          passphraseUtf8,
          blob,
          dbPath,
          bookId,
          borrowerId,
          lentDate,
          dueDate,
          returnedDate,
          notes,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInsertLoanConstMeta => const TaskConstMeta(
    debugName: "insert_loan",
    argNames: [
      "passphraseUtf8",
      "blob",
      "dbPath",
      "bookId",
      "borrowerId",
      "lentDate",
      "dueDate",
      "returnedDate",
      "notes",
    ],
  );

  @override
  Future<String> crateApiRewrapBlob({
    required List<int> oldPassphraseUtf8,
    required List<int> newPassphraseUtf8,
    required String blob,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(oldPassphraseUtf8, serializer);
          sse_encode_list_prim_u_8_loose(newPassphraseUtf8, serializer);
          sse_encode_String(blob, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_vault_rewrap_error,
        ),
        constMeta: kCrateApiRewrapBlobConstMeta,
        argValues: [oldPassphraseUtf8, newPassphraseUtf8, blob],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRewrapBlobConstMeta => const TaskConstMeta(
    debugName: "rewrap_blob",
    argNames: ["oldPassphraseUtf8", "newPassphraseUtf8", "blob"],
  );

  @override
  Future<VaultContents> crateApiUnlockAndReadVault({
    required List<int> passphraseUtf8,
    required String blob,
    required String dbPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(passphraseUtf8, serializer);
          sse_encode_String(blob, serializer);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vault_contents,
          decodeErrorData: sse_decode_vault_unlock_error,
        ),
        constMeta: kCrateApiUnlockAndReadVaultConstMeta,
        argValues: [passphraseUtf8, blob, dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUnlockAndReadVaultConstMeta => const TaskConstMeta(
    debugName: "unlock_and_read_vault",
    argNames: ["passphraseUtf8", "blob", "dbPath"],
  );

  @override
  Future<void> crateApiUpdateBorrower({
    required List<int> passphraseUtf8,
    required String blob,
    required String dbPath,
    required PlatformInt64 id,
    required String name,
    String? contact,
    String? notes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(passphraseUtf8, serializer);
          sse_encode_String(blob, serializer);
          sse_encode_String(dbPath, serializer);
          sse_encode_i_64(id, serializer);
          sse_encode_String(name, serializer);
          sse_encode_opt_String(contact, serializer);
          sse_encode_opt_String(notes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_vault_write_error,
        ),
        constMeta: kCrateApiUpdateBorrowerConstMeta,
        argValues: [passphraseUtf8, blob, dbPath, id, name, contact, notes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUpdateBorrowerConstMeta => const TaskConstMeta(
    debugName: "update_borrower",
    argNames: [
      "passphraseUtf8",
      "blob",
      "dbPath",
      "id",
      "name",
      "contact",
      "notes",
    ],
  );

  @override
  Future<void> crateApiUpdateLoan({
    required List<int> passphraseUtf8,
    required String blob,
    required String dbPath,
    required PlatformInt64 id,
    required PlatformInt64 bookId,
    required PlatformInt64 borrowerId,
    required PlatformInt64 lentDate,
    PlatformInt64? dueDate,
    PlatformInt64? returnedDate,
    String? notes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(passphraseUtf8, serializer);
          sse_encode_String(blob, serializer);
          sse_encode_String(dbPath, serializer);
          sse_encode_i_64(id, serializer);
          sse_encode_i_64(bookId, serializer);
          sse_encode_i_64(borrowerId, serializer);
          sse_encode_i_64(lentDate, serializer);
          sse_encode_opt_box_autoadd_i_64(dueDate, serializer);
          sse_encode_opt_box_autoadd_i_64(returnedDate, serializer);
          sse_encode_opt_String(notes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_vault_write_error,
        ),
        constMeta: kCrateApiUpdateLoanConstMeta,
        argValues: [
          passphraseUtf8,
          blob,
          dbPath,
          id,
          bookId,
          borrowerId,
          lentDate,
          dueDate,
          returnedDate,
          notes,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUpdateLoanConstMeta => const TaskConstMeta(
    debugName: "update_loan",
    argNames: [
      "passphraseUtf8",
      "blob",
      "dbPath",
      "id",
      "bookId",
      "borrowerId",
      "lentDate",
      "dueDate",
      "returnedDate",
      "notes",
    ],
  );

  @override
  Future<BiometricWrap> crateApiWrapForBiometric({
    required List<int> activeSecretUtf8,
    required String blob,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(activeSecretUtf8, serializer);
          sse_encode_String(blob, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_biometric_wrap,
          decodeErrorData: sse_decode_vault_biometric_error,
        ),
        constMeta: kCrateApiWrapForBiometricConstMeta,
        argValues: [activeSecretUtf8, blob],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWrapForBiometricConstMeta => const TaskConstMeta(
    debugName: "wrap_for_biometric",
    argNames: ["activeSecretUtf8", "blob"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BiometricWrap dco_decode_biometric_wrap(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BiometricWrap(
      secret: dco_decode_list_prim_u_8_strict(arr[0]),
      blob: dco_decode_String(arr[1]),
    );
  }

  @protected
  Borrower dco_decode_borrower(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Borrower(
      id: dco_decode_i_64(arr[0]),
      name: dco_decode_opt_String(arr[1]),
      contact: dco_decode_opt_String(arr[2]),
      notes: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<Borrower> dco_decode_list_borrower(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_borrower).toList();
  }

  @protected
  List<Loan> dco_decode_list_loan(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_loan).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  Loan dco_decode_loan(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return Loan(
      id: dco_decode_i_64(arr[0]),
      bookId: dco_decode_i_64(arr[1]),
      borrowerId: dco_decode_i_64(arr[2]),
      lentDate: dco_decode_opt_box_autoadd_i_64(arr[3]),
      dueDate: dco_decode_opt_box_autoadd_i_64(arr[4]),
      returnedDate: dco_decode_opt_box_autoadd_i_64(arr[5]),
      notes: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VaultBiometricError dco_decode_vault_biometric_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return VaultBiometricError_Corrupt(dco_decode_String(raw[1]));
      case 1:
        return VaultBiometricError_WrongPassphrase();
      case 2:
        return VaultBiometricError_Wrap(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  VaultContents dco_decode_vault_contents(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return VaultContents(
      borrowers: dco_decode_list_borrower(arr[0]),
      loans: dco_decode_list_loan(arr[1]),
    );
  }

  @protected
  VaultCreateError dco_decode_vault_create_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return VaultCreateError_AlreadyExists(dco_decode_String(raw[1]));
      case 1:
        return VaultCreateError_VaultOpen(dco_decode_String(raw[1]));
      case 2:
        return VaultCreateError_Wrap(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  VaultRewrapError dco_decode_vault_rewrap_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return VaultRewrapError_Corrupt(dco_decode_String(raw[1]));
      case 1:
        return VaultRewrapError_WrongPassphrase();
      case 2:
        return VaultRewrapError_Wrap(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  VaultUnlockError dco_decode_vault_unlock_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return VaultUnlockError_Corrupt(dco_decode_String(raw[1]));
      case 1:
        return VaultUnlockError_WrongPassphrase();
      case 2:
        return VaultUnlockError_VaultOpen(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  VaultWriteError dco_decode_vault_write_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return VaultWriteError_Corrupt(dco_decode_String(raw[1]));
      case 1:
        return VaultWriteError_WrongPassphrase();
      case 2:
        return VaultWriteError_VaultOpen(dco_decode_String(raw[1]));
      case 3:
        return VaultWriteError_Constraint(dco_decode_String(raw[1]));
      case 4:
        return VaultWriteError_NotFound();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BiometricWrap sse_decode_biometric_wrap(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_secret = sse_decode_list_prim_u_8_strict(deserializer);
    var var_blob = sse_decode_String(deserializer);
    return BiometricWrap(secret: var_secret, blob: var_blob);
  }

  @protected
  Borrower sse_decode_borrower(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    var var_contact = sse_decode_opt_String(deserializer);
    var var_notes = sse_decode_opt_String(deserializer);
    return Borrower(
      id: var_id,
      name: var_name,
      contact: var_contact,
      notes: var_notes,
    );
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<Borrower> sse_decode_list_borrower(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Borrower>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_borrower(deserializer));
    }
    return ans_;
  }

  @protected
  List<Loan> sse_decode_list_loan(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Loan>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_loan(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Loan sse_decode_loan(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_bookId = sse_decode_i_64(deserializer);
    var var_borrowerId = sse_decode_i_64(deserializer);
    var var_lentDate = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_dueDate = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_returnedDate = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_notes = sse_decode_opt_String(deserializer);
    return Loan(
      id: var_id,
      bookId: var_bookId,
      borrowerId: var_borrowerId,
      lentDate: var_lentDate,
      dueDate: var_dueDate,
      returnedDate: var_returnedDate,
      notes: var_notes,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VaultBiometricError sse_decode_vault_biometric_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return VaultBiometricError_Corrupt(var_field0);
      case 1:
        return VaultBiometricError_WrongPassphrase();
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return VaultBiometricError_Wrap(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  VaultContents sse_decode_vault_contents(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_borrowers = sse_decode_list_borrower(deserializer);
    var var_loans = sse_decode_list_loan(deserializer);
    return VaultContents(borrowers: var_borrowers, loans: var_loans);
  }

  @protected
  VaultCreateError sse_decode_vault_create_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return VaultCreateError_AlreadyExists(var_field0);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return VaultCreateError_VaultOpen(var_field0);
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return VaultCreateError_Wrap(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  VaultRewrapError sse_decode_vault_rewrap_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return VaultRewrapError_Corrupt(var_field0);
      case 1:
        return VaultRewrapError_WrongPassphrase();
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return VaultRewrapError_Wrap(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  VaultUnlockError sse_decode_vault_unlock_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return VaultUnlockError_Corrupt(var_field0);
      case 1:
        return VaultUnlockError_WrongPassphrase();
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return VaultUnlockError_VaultOpen(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  VaultWriteError sse_decode_vault_write_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return VaultWriteError_Corrupt(var_field0);
      case 1:
        return VaultWriteError_WrongPassphrase();
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return VaultWriteError_VaultOpen(var_field0);
      case 3:
        var var_field0 = sse_decode_String(deserializer);
        return VaultWriteError_Constraint(var_field0);
      case 4:
        return VaultWriteError_NotFound();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_biometric_wrap(BiometricWrap self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.secret, serializer);
    sse_encode_String(self.blob, serializer);
  }

  @protected
  void sse_encode_borrower(Borrower self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_opt_String(self.name, serializer);
    sse_encode_opt_String(self.contact, serializer);
    sse_encode_opt_String(self.notes, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_borrower(List<Borrower> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_borrower(item, serializer);
    }
  }

  @protected
  void sse_encode_list_loan(List<Loan> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_loan(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_loan(Loan self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_i_64(self.bookId, serializer);
    sse_encode_i_64(self.borrowerId, serializer);
    sse_encode_opt_box_autoadd_i_64(self.lentDate, serializer);
    sse_encode_opt_box_autoadd_i_64(self.dueDate, serializer);
    sse_encode_opt_box_autoadd_i_64(self.returnedDate, serializer);
    sse_encode_opt_String(self.notes, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_vault_biometric_error(
    VaultBiometricError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case VaultBiometricError_Corrupt(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case VaultBiometricError_WrongPassphrase():
        sse_encode_i_32(1, serializer);
      case VaultBiometricError_Wrap(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_vault_contents(VaultContents self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_borrower(self.borrowers, serializer);
    sse_encode_list_loan(self.loans, serializer);
  }

  @protected
  void sse_encode_vault_create_error(
    VaultCreateError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case VaultCreateError_AlreadyExists(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case VaultCreateError_VaultOpen(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case VaultCreateError_Wrap(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_vault_rewrap_error(
    VaultRewrapError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case VaultRewrapError_Corrupt(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case VaultRewrapError_WrongPassphrase():
        sse_encode_i_32(1, serializer);
      case VaultRewrapError_Wrap(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_vault_unlock_error(
    VaultUnlockError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case VaultUnlockError_Corrupt(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case VaultUnlockError_WrongPassphrase():
        sse_encode_i_32(1, serializer);
      case VaultUnlockError_VaultOpen(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_vault_write_error(
    VaultWriteError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case VaultWriteError_Corrupt(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case VaultWriteError_WrongPassphrase():
        sse_encode_i_32(1, serializer);
      case VaultWriteError_VaultOpen(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case VaultWriteError_Constraint(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_String(field0, serializer);
      case VaultWriteError_NotFound():
        sse_encode_i_32(4, serializer);
    }
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
