//! Test-fixture generator (NOT part of the shipped FFI/lib surface).
//!
//! Produces a small encrypted `borrowers.db` + matching `backup_blob` using a
//! PUBLIC, throwaway passphrase and FAKE rows, so the full vault unlock chain
//! (Argon2id -> AES-256-GCM -> SQLCipher `sqlite3_key`) can be proven
//! hermetically in CI without ever committing a real secret or real borrower
//! PII (AGENTS.md §2a / §12.7).
//!
//! Deterministic by design: fixed salt/iv/key bytes, so re-running reproduces a
//! byte-identical fixture. Run once and commit the outputs:
//!
//!   cargo run --release --example gen_test_vault -- <out_dir>
//!
//! Outputs in <out_dir>:
//!   test_borrowers.db   SQLCipher DB encrypted under the derived vault key
//!   test_backup_blob    base64(salt).base64(iv).base64(ciphertext)
//!   README.txt          the public passphrase + provenance note

use aes_gcm::aead::{Aead, KeyInit, Payload};
use aes_gcm::{Aes256Gcm, Nonce};
use argon2::{Algorithm, Argon2, Params, Version};
use base64::Engine;
use rusqlite::Connection;
use std::ffi::{c_int, c_void};
use std::fs;
use std::path::Path;

// Must match crate::crypto constants exactly.
const ARGON2_M_COST_KIB: u32 = 65_536;
const ARGON2_T_COST: u32 = 3;
const ARGON2_PARALLELISM: u32 = 1;
const KEY_BYTES: usize = 32;

/// PUBLIC throwaway passphrase — safe to commit. NOT a real user secret.
const TEST_PASSPHRASE: &str = "test-pass-not-secret";

// Fixed inputs for a reproducible fixture (no randomness needed for a fixture).
const SALT: [u8; 16] = [0x42; 16];
const IV: [u8; 12] = [0x24; 12];
// The 32-byte vault key that SQLCipher will be keyed with. Arbitrary fixed bytes.
const VAULT_KEY: [u8; 32] = [
    0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10,
    0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x20,
];

extern "C" {
    fn sqlite3_key(
        db: *mut libsqlite3_sys::sqlite3,
        p_key: *const c_void,
        n_key: c_int,
    ) -> c_int;
}

fn main() {
    let out_dir = std::env::args()
        .nth(1)
        .expect("usage: gen_test_vault <out_dir>");
    let out = Path::new(&out_dir);
    fs::create_dir_all(out).expect("create out dir");

    // 1. Derive the KEK from the public passphrase + fixed salt (same params as
    //    crate::crypto), then AES-256-GCM-encrypt the fixed vault key into the
    //    blob ciphertext (this is the inverse of `unwrap_vault_key`).
    let params = Params::new(
        ARGON2_M_COST_KIB,
        ARGON2_T_COST,
        ARGON2_PARALLELISM,
        Some(KEY_BYTES),
    )
    .expect("argon2 params");
    let argon = Argon2::new(Algorithm::Argon2id, Version::V0x13, params);
    let mut kek = [0u8; KEY_BYTES];
    argon
        .hash_password_into(TEST_PASSPHRASE.as_bytes(), &SALT, &mut kek)
        .expect("argon2 derive");

    let cipher = Aes256Gcm::new_from_slice(&kek).expect("aes key");
    let nonce = Nonce::from_slice(&IV);
    let ciphertext = cipher
        .encrypt(nonce, Payload { msg: &VAULT_KEY, aad: b"" })
        .expect("gcm encrypt");

    let b64 = base64::engine::general_purpose::STANDARD;
    let blob = format!(
        "{}.{}.{}",
        b64.encode(SALT),
        b64.encode(IV),
        b64.encode(&ciphertext),
    );
    fs::write(out.join("test_backup_blob"), &blob).expect("write blob");

    // 2. Create an encrypted borrowers.db keyed with the SAME raw vault key the
    //    blob unwraps to, via SQLCipher `sqlite3_key` (the zetetic mechanism).
    let db_path = out.join("test_borrowers.db");
    let _ = fs::remove_file(&db_path);
    let conn = Connection::open(&db_path).expect("open db");
    let rc = unsafe {
        sqlite3_key(
            conn.handle(),
            VAULT_KEY.as_ptr() as *const c_void,
            VAULT_KEY.len() as c_int,
        )
    };
    assert_eq!(rc, 0, "sqlite3_key failed");

    // Schema mirrors BorrowersDatabase/1.json (borrowers + loans).
    conn.execute_batch(
        "CREATE TABLE borrowers(
            id INTEGER PRIMARY KEY NOT NULL, name TEXT NOT NULL,
            contact TEXT, notes TEXT);
         CREATE TABLE loans(
            id INTEGER PRIMARY KEY NOT NULL, book_id INTEGER NOT NULL,
            borrower_id INTEGER NOT NULL, lent_date INTEGER NOT NULL,
            due_date INTEGER, returned_date INTEGER, notes TEXT);
         INSERT INTO borrowers(id,name,contact,notes)
            VALUES (1,'Test Borrower','555-0100','fixture row');
         INSERT INTO loans(id,book_id,borrower_id,lent_date,due_date,notes)
            VALUES (10,7,1,1700000000000,1700600000000,'fixture loan');",
    )
    .expect("create + seed");
    drop(conn);

    fs::write(
        out.join("README.txt"),
        format!(
            "Hermetic test vault fixture (generated by examples/gen_test_vault.rs).\n\
             Passphrase: {TEST_PASSPHRASE}\n\
             This is a PUBLIC throwaway passphrase with FAKE rows — NOT a real\n\
             secret and NOT real PII. Safe to commit. Regenerate byte-identically\n\
             with: cargo run --release --example gen_test_vault -- <out_dir>\n",
        ),
    )
    .expect("write readme");

    println!("Wrote fixture to {}", out.display());
}
